version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data/db:/var/lib/ecommerceweb
    ports:
      - 3306:3306

    environment:
      - MYSQL_DB=testDB
      - MYSQL_ROOT_PASSWORD=123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
